volumes:
  web:

services:
  snipeit:
    image: pirasbro/snipe-it:5.3.0-fpm-alpine
    environment:
      # SnipeIT settings
      APP_URL: localhost:8080
      APP_KEY: base64:CdNywz90QeGfAvL4nw7sqHwr9nI8v4z+yYcWpEgH+4g=
      # Database settings
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: snipeit
      DB_USERNAME: dev
      DB_PASSWORD: dev
      # Session settings
      SECURE_COOKIES: "false"
    volumes:
      - web:/var/www/html
    depends_on:
      - mariadb

  nginx:
    image: docker.io/nginx:1.21.3-alpine
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 8080
      NGINX_UPSTREAM: snipeit_php-fpm:9000
    ports:
      - "8080:8080"
    volumes:
      - web:/var/www/html
      # Nginx default no-ssl config template
      - "./no-ssl.conf.template:/etc/nginx/templates/default.conf.template:ro"
    depends_on:
      - snipeit

  mariadb:
    image: docker.io/mariadb:10.6.4-focal
    user: mysql:mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: snipeit
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - database:/var/lib/mysql