volumes:
  snipeit_data:
  web:
  database:

services:
  snipeit:
    image: docker.io/pirasbro/snipe-it:latest
    environment:
      # SnipeIT settings
      APP_URL: localhost:8080
      APP_KEY: base64:CdNywz90QeGfAvL4nw7sqHwr9nI8v4z+yYcWpEgH+4g=
      # Database settings
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: snipeit
      DB_USERNAME: dev
      DB_PASSWORD: dev
      # Session settings
      SECURE_COOKIES: "false"
    volumes:
      - web:/var/www/html
      - snipeit_data:/var/lib/snipeit
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    image: docker.io/nginx:alpine
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 8080
      NGINX_UPSTREAM: snipeit:9000
    ports:
      - "8080:8080"
    volumes:
      - web:/var/www/html
      # Nginx default no-ssl config template
      - "./no-ssl.conf.template:/etc/nginx/templates/default.conf.template:ro"
    depends_on:
      - snipeit

  mariadb:
    image: docker.io/mariadb:latest
    user: mysql:mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: snipeit
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - database:/var/lib/mysql